#include <stdio.h>
#include <stdlib.h>
#include <math.h>

/*The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/
int main(void)
{
	int metritis = 1;
	int counter = 0;
	int arithmos = 0;
	int PithDieretes = 0;
	int found = 0;
	int dierethike;
	while(found == 0)
	{
		arithmos = arithmos + metritis;
		printf("Arithmos:%d\n", arithmos);
		//system("pause");
		dierethike = 0;
		for(PithDieretes = 1; PithDieretes <= (sqrt(arithmos)); PithDieretes++)
		{
			if(arithmos % PithDieretes == 0)
			{
				dierethike++;
				if(dierethike == 250)
				{
					found = 1;
					printf("O arithmos einai: %d\n", arithmos);
				}
			}
		}
		if(dierethike == 250)
		{
			found = 1;
			printf("O arithmos einai: %d\n", arithmos);
		}
		metritis++;
	}
	printf("O arithmos einai: %d\n", arithmos);
}
